# Generated by Django 5.0.7 on 2024-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('funding_agency', models.CharField(max_length=100)),
                ('project_grant', models.IntegerField(help_text='Grant amount in Rs')),
                ('letter_no', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('cd_pi', models.TextField()),
                ('project_duration_years', models.IntegerField()),
                ('project_duration_months', models.IntegerField()),
            ],
        ),
    ]
