# Generated by Django 5.0.7 on 2024-07-30 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0002_fundedproject_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundedproject',
            name='cd_pi',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='FundedProjectSanctioned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('funding_agency', models.CharField(max_length=100)),
                ('project_grant', models.IntegerField(help_text='Grant amount in Rs')),
                ('letter_no', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('cd_pi', models.CharField(max_length=200)),
                ('project_duration_years', models.IntegerField()),
                ('project_duration_months', models.IntegerField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='project_proofs/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funded_project_sanctioned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
