# Generated by Django 5.0.7 on 2024-07-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0003_alter_fundedproject_cd_pi_fundedprojectsanctioned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundedprojectsanctioned',
            old_name='project_duration_months',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='fundedprojectsanctioned',
            old_name='project_duration_years',
            new_name='start_date',
        ),
        migrations.CreateModel(
            name='ConsultancyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('amount_sanctioned', models.IntegerField(help_text='Amount sanctioned in Rs')),
                ('letter_amount', models.IntegerField(help_text='Letter amount in Rs')),
                ('date_of_sanction', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='consultancy_proofs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
