# Generated by Django 5.0.7 on 2024-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0004_rename_project_duration_months_fundedprojectsanctioned_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('faculty_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('amount_credited', models.IntegerField(help_text='Amount credited in Rs')),
                ('letter_no', models.IntegerField()),
                ('date_of_sanction', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='seedmoney_proofs/')),
            ],
        ),
    ]
