# Generated by Django 5.0.7 on 2024-07-30 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0006_seedmoney_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_inventors', models.TextField(help_text='Enter names of co-inventors (students and faculty)')),
                ('title', models.CharField(max_length=200)),
                ('filing_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('proof', models.FileField(blank=True, null=True, upload_to='patent_proofs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
