# Generated by Django 5.0.7 on 2024-08-05 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0008_startup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancyproject',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/consultancy_proofs/'),
        ),
        migrations.AlterField(
            model_name='fundedproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funded_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundedprojectsanctioned',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/project_proofs/'),
        ),
        migrations.AlterField(
            model_name='fundedprojectsanctioned',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funded_project_sanctioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patent',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/patent_proofs/'),
        ),
        migrations.AlterField(
            model_name='seedmoney',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/seedmoney_proofs/'),
        ),
        migrations.CreateModel(
            name='ScopusWosPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(help_text='Enter names of authors and co-authors')),
                ('title', models.CharField(max_length=300)),
                ('journal_name', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('indexed_in', models.CharField(choices=[('Scopus', 'Scopus'), ('WoS', 'Web of Science')], max_length=50)),
                ('if_value', models.CharField(help_text='Impact Factor value', max_length=10)),
                ('collaborator', models.CharField(help_text='Academic/Industry with name and designation', max_length=300)),
                ('full_paper_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopus_wos_publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
