# Generated by Django 5.0.7 on 2024-08-05 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0009_alter_consultancyproject_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('chapter_title', models.CharField(max_length=300)),
                ('book_title', models.CharField(max_length=300)),
                ('publisher_name', models.CharField(max_length=200)),
                ('chapter_number', models.IntegerField()),
                ('page_number', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('collaborators', models.TextField(help_text='Academic/Industry with name and designation')),
                ('full_paper_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
