# Generated by Django 5.0.7 on 2024-08-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0010_bookchapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceProceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(help_text='Enter names of authors')),
                ('title', models.CharField(max_length=300)),
                ('conference_name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('isbn_issn', models.CharField(help_text='ISBN or ISSN number', max_length=20)),
                ('collaborators', models.TextField(help_text='Academic/Industry with name and designation')),
                ('full_paper_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_proceedings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
