# Generated by Django 5.0.7 on 2024-08-05 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0011_conferenceproceeding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name_designation', models.CharField(help_text='Name of the faculty & designation', max_length=300)),
                ('event_type', models.CharField(choices=[('On Campus', 'On Campus'), ('Outside KITS', 'Outside KITS')], max_length=100)),
                ('topic_title', models.CharField(help_text='Topic/Title of the event', max_length=300)),
                ('date_venue', models.CharField(help_text='Date and venue of the event', max_length=300)),
                ('delegates_count', models.IntegerField(help_text='Number of delegates participated')),
                ('report_link', models.URLField(blank=True, help_text='Link to the report', null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='guest_lecture_certificates/')),
                ('invitation_letter', models.FileField(blank=True, null=True, upload_to='guest_lecture_letters/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_lectures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
