# Generated by Django 5.0.7 on 2024-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0012_guestlecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlecture',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/guest_lecture_certificates/'),
        ),
        migrations.AlterField(
            model_name='guestlecture',
            name='invitation_letter',
            field=models.FileField(blank=True, null=True, upload_to='images/guest_lecture_letters/'),
        ),
    ]
