# Generated by Django 5.0.7 on 2024-08-05 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0013_alter_guestlecture_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Name of the faculty', max_length=200)),
                ('program_nature', models.CharField(help_text='Nature of the program', max_length=200)),
                ('program_title', models.CharField(help_text='Title of the program', max_length=300)),
                ('date', models.DateField(help_text='Date of the event')),
                ('sponsoring_agencies', models.CharField(help_text='Sponsoring agencies', max_length=300)),
                ('certificate_link', models.URLField(blank=True, help_text='Link to the certificate', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_event_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
