# Generated by Django 5.0.7 on 2024-08-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0015_facultyeventparticipationoffcampus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOrganized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Name of the faculty', max_length=200)),
                ('event_type', models.CharField(help_text='Type of event', max_length=100)),
                ('program_title', models.CharField(help_text='Title of the program', max_length=300)),
                ('date_venue', models.CharField(help_text='Date and venue of the program', max_length=300)),
                ('resource_person', models.CharField(help_text='Name of the resource person', max_length=200)),
                ('sponsorship_income', models.CharField(help_text='Sponsorship if any / Income generated', max_length=300)),
                ('delegates_count', models.IntegerField(help_text='Number of delegates participated')),
                ('report_proof', models.FileField(blank=True, help_text='Upload report or proof of the event', null=True, upload_to='program_proofs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs_organized', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
