# Generated by Django 5.0.7 on 2024-08-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0016_programorganized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeGeneratedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(help_text='Name of the program', max_length=200)),
                ('event_title', models.CharField(help_text='Title of the event', max_length=300)),
                ('event_level', models.CharField(choices=[('National', 'National'), ('International', 'International')], help_text='National or International', max_length=50)),
                ('date', models.DateField(help_text='Date of the event')),
                ('resource_person_designation', models.CharField(help_text='Resource person & Designation', max_length=300)),
                ('delegates_count', models.IntegerField(help_text='Number of delegates participated')),
                ('income_generated', models.DecimalField(decimal_places=2, help_text='Income generated (Rs)', max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_generated_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
