# Generated by Django 5.0.7 on 2024-08-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0018_alumniinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMoocCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('virtual_platform', models.CharField(choices=[('NPTEL', 'NPTEL'), ('Coursera', 'Coursera'), ('edX', 'edX')], max_length=50)),
                ('course_title', models.CharField(max_length=300)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('certificate_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mooc_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_title', 'virtual_platform')},
            },
        ),
    ]
