# Generated by Django 5.0.7 on 2024-08-05 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0019_facultymooccourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementHigherStudiesEntrepreneurship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_designation', models.CharField(max_length=200)),
                ('resource_person', models.CharField(max_length=200)),
                ('resource_person_details', models.CharField(help_text='Designation/Company/Organization details', max_length=300)),
                ('program_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('student_participants', models.PositiveIntegerField()),
                ('report_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_higher_studies_entrepreneurship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
