# Generated by Django 5.0.7 on 2024-08-06 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0020_placementhigherstudiesentrepreneurship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySpiritualActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_designation', models.CharField(max_length=200)),
                ('program_name', models.CharField(max_length=300)),
                ('place_and_date', models.CharField(max_length=300)),
                ('beneficiaries_count', models.PositiveIntegerField()),
                ('report_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_spiritual_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Community & Spiritual Activities',
            },
        ),
    ]
