# Generated by Django 5.0.7 on 2024-08-06 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0022_companyvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('mentor_name', models.CharField(max_length=200)),
                ('host_institution', models.CharField(max_length=300)),
                ('city_country', models.CharField(max_length=200)),
                ('period_duration', models.CharField(max_length=200)),
                ('certificate_photos_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'International Internships (IAESTE)',
            },
        ),
    ]
