# Generated by Django 5.0.7 on 2024-08-06 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0023_internationalinternship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSeedMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('project_title', models.CharField(max_length=300)),
                ('amount_sanctioned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('letter_no_and_date', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('proof_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_seed_money', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seed Money for Students',
            },
        ),
    ]
