# Generated by Django 5.0.7 on 2024-08-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0024_studentseedmoney'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDevelopedByStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(help_text='Registration number of the student', max_length=50)),
                ('student_name', models.CharField(help_text='Name of the student', max_length=200)),
                ('product_name', models.CharField(help_text='Name of the prototype/product', max_length=300)),
                ('area_of_application', models.CharField(help_text='Area of application for the product', max_length=200)),
                ('brief_description', models.TextField(help_text='Brief description of the product')),
                ('proof_link', models.URLField(help_text='Link to proof or documentation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products Developed by Students',
            },
        ),
    ]
