# Generated by Django 5.0.7 on 2024-08-06 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0025_productdevelopedbystudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_details', models.CharField(help_text='Name of student(s) and registration number(s)', max_length=300)),
                ('startup_title', models.CharField(help_text='Title of the startup', max_length=200)),
                ('investors', models.CharField(help_text='Names of investors', max_length=300)),
                ('registration_info', models.CharField(help_text='Registration number and date', max_length=200)),
                ('proof_link', models.URLField(help_text='Link to proof or documentation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Startups',
            },
        ),
    ]
