# Generated by Django 5.0.7 on 2024-08-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0026_studentstartup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveExamSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(help_text='Registration number / Roll number of examination', max_length=50)),
                ('student_name', models.CharField(help_text='Name of selected/qualified student', max_length=200)),
                ('exam_type', models.CharField(choices=[('NET', 'NET'), ('SLET', 'SLET'), ('GATE', 'GATE'), ('GMAT', 'GMAT'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('JAM', 'JAM'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CIVIL_SERVICES', 'Civil Services'), ('STATE_GOVT', 'State Government Exams'), ('OTHER', 'Other')], max_length=20)),
                ('other_exam', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100, null=True)),
                ('proof_link', models.URLField(help_text='Link to proof or documentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_exam_successes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Competitive Exam Successes',
            },
        ),
    ]
