# Generated by Django 5.0.7 on 2024-08-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0030_studentsportsparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(help_text='Registration number of the student', max_length=50)),
                ('student_name', models.CharField(help_text='Name of the student', max_length=200)),
                ('cadet_name', models.CharField(help_text='Name of the cadet', max_length=200)),
                ('rank', models.CharField(help_text='Rank of the cadet', max_length=100)),
                ('participation_type', models.CharField(choices=[('CAMP', 'Camp'), ('PARADE', 'Parade'), ('EVENT', 'Event'), ('EXAM', 'Exam')], help_text='Type of participation', max_length=10)),
                ('event_details', models.CharField(help_text='Details of the camp/parade/event/exam', max_length=300)),
                ('award', models.CharField(blank=True, help_text='Award received, if any', max_length=200, null=True)),
                ('certificate_link', models.URLField(help_text='Link to the certificate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncc_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NCC Participations',
            },
        ),
    ]
