# Generated by Django 5.0.7 on 2024-08-06 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0031_nccparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_visit', models.CharField(help_text='Place of industrial visit', max_length=300)),
                ('date_of_visit', models.DateField(help_text='Date of the visit')),
                ('number_of_students', models.PositiveIntegerField(help_text='Number of students who participated')),
                ('number_of_faculty', models.PositiveIntegerField(help_text='Number of faculty members who participated')),
                ('outcome', models.TextField(help_text='Outcome of the industrial visit')),
                ('report_link', models.URLField(help_text='Link to the visit report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industrial_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Industrial Visits',
            },
        ),
    ]
