# Generated by Django 5.1 on 2024-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0033_alter_fundedprojectsanctioned_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopuswospublication',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scopuswospublication',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scopuswospublication',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopuswospublication',
            name='full_paper_link',
            field=models.FileField(upload_to='publications/'),
        ),
    ]
