# Generated by Django 5.1 on 2024-08-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0034_scopuswospublication_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='full_paper_link',
        ),
        migrations.AlterField(
            model_name='scopuswospublication',
            name='full_paper_link',
            field=models.URLField(),
        ),
    ]
