# Generated by Django 5.1 on 2024-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0035_remove_bookchapter_collaborators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceproceeding',
            name='full_paper_link',
        ),
        migrations.RemoveField(
            model_name='conferenceproceeding',
            name='isbn_issn',
        ),
        migrations.AddField(
            model_name='conferenceproceeding',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/conference_proofs/'),
        ),
    ]
