# Generated by Django 5.1 on 2024-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0036_remove_conferenceproceeding_full_paper_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalinternship',
            name='certificate_photos_link',
        ),
        migrations.AddField(
            model_name='internationalinternship',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/conference_proofs/'),
        ),
    ]
