# Generated by Django 5.1 on 2024-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0038_rename_faculty_name_studentseedmoney_reg_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdevelopedbystudent',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='productdevelopedbystudent',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/conference_proofs/'),
        ),
    ]
