# Generated by Django 5.1 on 2024-08-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0039_remove_productdevelopedbystudent_proof_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstartup',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='studentstartup',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='images/conference_proofs/'),
        ),
        migrations.AlterField(
            model_name='studentstartup',
            name='registration_info',
            field=models.DateField(),
        ),
    ]
