# Generated by Django 5.1 on 2024-08-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0040_remove_studentstartup_proof_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiveexamsuccess',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='competitiveexamsuccess',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof or documentation', null=True, upload_to='competitive_exam_proofs/'),
        ),
        migrations.AddField(
            model_name='competitiveexamsuccess',
            name='roll_no',
            field=models.CharField(blank=True, help_text="Student's roll number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitiveexamsuccess',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('OTHER', 'Other')], help_text='Year of study', max_length=10, null=True),
        ),
    ]
