# Generated by Django 5.1 on 2024-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0042_remove_studenteventparticipation_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcocurricularparticipation',
            name='certificate_link',
        ),
        migrations.RemoveField(
            model_name='studentcocurricularparticipation',
            name='host_institute_and_place',
        ),
        migrations.AddField(
            model_name='studentcocurricularparticipation',
            name='city',
            field=models.CharField(blank=True, help_text='City of the event', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcocurricularparticipation',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the event', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcocurricularparticipation',
            name='host_institute',
            field=models.CharField(blank=True, help_text='Host institute', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcocurricularparticipation',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof or documentation', null=True, upload_to='co_curricular_proofs/'),
        ),
        migrations.AlterField(
            model_name='studenteventparticipation',
            name='host_institute',
            field=models.CharField(help_text='Host institute', max_length=200),
        ),
    ]
