# Generated by Django 5.1 on 2024-08-09 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0043_remove_studentcocurricularparticipation_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsportsparticipation',
            name='certificate_link',
        ),
        migrations.RemoveField(
            model_name='studentsportsparticipation',
            name='organizing_institution_and_place',
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='city',
            field=models.CharField(blank=True, help_text='City of the event', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='country',
            field=models.CharField(blank='True', help_text='Country of the event', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the event'),
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, help_text='End date of the event'),
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='organizing_institution',
            field=models.CharField(blank=True, help_text='Organizing institution', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsportsparticipation',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof or documentation', null=True, upload_to='sports_proofs/'),
        ),
        migrations.AlterField(
            model_name='studentcocurricularparticipation',
            name='host_institute',
            field=models.CharField(default='Unknown', help_text='Host institute', max_length=200),
        ),
    ]
