# Generated by Django 5.1 on 2024-08-09 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0044_remove_studentsportsparticipation_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nccparticipation',
            name='certificate_link',
        ),
        migrations.RemoveField(
            model_name='nccparticipation',
            name='event_details',
        ),
        migrations.RemoveField(
            model_name='nccparticipation',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='nccparticipation',
            name='student_name',
        ),
        migrations.AddField(
            model_name='nccparticipation',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Date of participation'),
        ),
        migrations.AddField(
            model_name='nccparticipation',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof or documentation', null=True, upload_to='ncc_proofs/'),
        ),
    ]
