# Generated by Django 5.1 on 2024-08-09 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0045_remove_nccparticipation_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialvisit',
            name='date_of_visit',
        ),
        migrations.RemoveField(
            model_name='industrialvisit',
            name='number_of_faculty',
        ),
        migrations.RemoveField(
            model_name='industrialvisit',
            name='report_link',
        ),
        migrations.AddField(
            model_name='industrialvisit',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the visit'),
        ),
        migrations.AddField(
            model_name='industrialvisit',
            name='date_to',
            field=models.DateField(blank=True, help_text='End date of the visit', null=True),
        ),
        migrations.AddField(
            model_name='industrialvisit',
            name='faculty_members',
            field=models.TextField(default='To be updated', help_text='Names of faculty members who participated'),
        ),
        migrations.AddField(
            model_name='industrialvisit',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof or documentation', null=True, upload_to='industrial_visit_proofs/'),
        ),
    ]
