# Generated by Django 5.1 on 2024-08-09 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0046_remove_industrialvisit_date_of_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nccparticipation',
            name='date',
        ),
        migrations.AddField(
            model_name='nccparticipation',
            name='date_from',
            field=models.DateField(default=datetime.date.today, help_text='Start date of participation'),
        ),
        migrations.AddField(
            model_name='nccparticipation',
            name='date_to',
            field=models.DateField(default=datetime.date.today, help_text='End date of participation'),
        ),
    ]
