# Generated by Django 5.1 on 2024-08-11 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0047_remove_nccparticipation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlecture',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='date_venue',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='delegates_count',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='faculty_name_designation',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='invitation_letter',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='report_link',
        ),
        migrations.RemoveField(
            model_name='guestlecture',
            name='topic_title',
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='lecture_type',
            field=models.CharField(choices=[('FDP', 'FDP'), ('Webinar', 'Webinar'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='report_certificate',
            field=models.FileField(blank=True, null=True, upload_to='guest_lecture_reports/'),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='topic',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='venue',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='guestlecture',
            name='event_type',
            field=models.CharField(choices=[('Internal', 'Internal Event'), ('External', 'External Event')], default='Internal', max_length=10),
        ),
    ]
