# Generated by Django 5.1 on 2024-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0050_remove_facultyeventparticipationoffcampus_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programorganized',
            name='date_venue',
        ),
        migrations.RemoveField(
            model_name='programorganized',
            name='report_proof',
        ),
        migrations.RemoveField(
            model_name='programorganized',
            name='sponsorship_income',
        ),
        migrations.AddField(
            model_name='programorganized',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programorganized',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programorganized',
            name='mode',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=10),
        ),
        migrations.AddField(
            model_name='programorganized',
            name='report_certificate',
            field=models.FileField(blank=True, null=True, upload_to='program_certificates/'),
        ),
        migrations.AddField(
            model_name='programorganized',
            name='sponsorships',
            field=models.CharField(blank=True, help_text='Sponsorships if any', max_length=300),
        ),
        migrations.AddField(
            model_name='programorganized',
            name='venue',
            field=models.CharField(blank=True, help_text='Enter the Venue', max_length=300),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='delegates_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of delegate participants'),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='event_type',
            field=models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Conference', 'Conference')], default='FDP', max_length=20),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='faculty_name',
            field=models.CharField(blank=True, help_text='Name of the faculty', max_length=200),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='program_title',
            field=models.CharField(blank=True, help_text='Title of the program', max_length=300),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='resource_person',
            field=models.CharField(blank=True, help_text='Name of the resource person', max_length=200),
        ),
    ]
