# Generated by Django 5.1 on 2024-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0051_remove_programorganized_date_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymooccourse',
            name='certificate_link',
        ),
        migrations.RemoveField(
            model_name='facultymooccourse',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='facultymooccourse',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='facultymooccourse',
            name='report_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/faculty_mooc/'),
        ),
        migrations.AlterField(
            model_name='programorganized',
            name='report_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/program_certificates/'),
        ),
    ]
