# Generated by Django 5.1 on 2024-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0052_remove_facultymooccourse_certificate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinteraction',
            name='report_link',
            field=models.FileField(blank=True, null=True, upload_to='images/alumini/'),
        ),
    ]
