# Generated by Django 5.1 on 2024-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0054_remove_placementhigherstudiesentrepreneurship_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementhigherstudiesentrepreneurship',
            name='category',
            field=models.CharField(blank=True, choices=[('Placement', 'Placement'), ('Higher Studies', 'Higher Studies'), ('Entrepreneurship', 'Entrepreneurship')], default='Placement', max_length=20, null=True),
        ),
    ]
