# Generated by Django 5.1 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0055_placementhigherstudiesentrepreneurship_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityspiritualactivity',
            name='faculty_designation',
        ),
        migrations.RemoveField(
            model_name='communityspiritualactivity',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='communityspiritualactivity',
            name='place_and_date',
        ),
        migrations.RemoveField(
            model_name='communityspiritualactivity',
            name='report_link',
        ),
        migrations.AddField(
            model_name='communityspiritualactivity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('community', 'Community'), ('spiritual', 'Spiritual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communityspiritualactivity',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityspiritualactivity',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityspiritualactivity',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='communityspiritualactivity',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='community_spiritual_proofs/'),
        ),
        migrations.AlterField(
            model_name='communityspiritualactivity',
            name='beneficiaries_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityspiritualactivity',
            name='program_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
