# Generated by Django 5.1 on 2024-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0056_remove_communityspiritualactivity_faculty_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvisit',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='companyvisit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='companyvisit',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvisit',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyvisit',
            name='report_link',
            field=models.FileField(blank=True, null=True, upload_to='community_spiritual_proofs/'),
        ),
    ]
