# Generated by Django 5.1 on 2024-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_projects', '0057_remove_companyvisit_faculty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomegeneratedprogram',
            name='date',
        ),
        migrations.AddField(
            model_name='incomegeneratedprogram',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the event', null=True),
        ),
        migrations.AddField(
            model_name='incomegeneratedprogram',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the event', null=True),
        ),
    ]
